name: Gibberish-Ultra
main: com.fawkes.plugin.Gibberish
version: 0.1
commands:
  gibberish:
    description: Enable / disable gibberish talk!
    permission: gibberish.use
    usage: /gibberish
    permission-message: You don't have permission to do this.
    